version: '3'

services:
  db:
    image: postgres
    container_name: db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - 5434:5432

volumes:
  postgres_data:
