# -*- coding: utf-8 -*-
"""Initial Migration.

Revision ID: 8d6a336014f2
Revises:
Create Date: 2022-06-10 08:59:48.233492

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '8d6a336014f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():  # noqa: D103  # pylint: disable=C0116
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():  # noqa: D103  # pylint: disable=C0116
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
